version: 0.2

phases:
  pre_build:
    commands:
      - yum install -y yum-utils
      - yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
      - yum -y install terraform
        
  build:
    commands:
      - export AWS_ACCESS_KEY_ID=$ACCESS
      - export AWS_SECRET_ACCESS_KEY=$SECRET
      - echo $ACCESS $SECRET
      - aws configure set aws_access_key_id $ACCESS
      - aws configure set aws_secret_access_key $SECRET
      - cd terraform
      - terraform init
      - terraform apply --auto-approve
      # - terraform destroy --auto-approve
        
  post_build:
    commands:
      - echo terraform $TF_COMMAND completed on '$date'~